import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';
import { log, isVerbose } from '../utils/logger.js';
import { loadConfig, saveConfig, getToolPaths } from '../utils/config.js';

const __dirname = path.dirname(new URL(import.meta.url).pathname);
const registryDir = path.resolve(__dirname, '..', '..', 'registry');

interface McpEntry {
  id: string;
  name: string;
  description: string;
  install: string;
  npxCommand?: string[];
  command: string;
  args?: string[];
  requiresEnv: string[];
  setupSteps?: string[];
  envSetup?: string;
  env?: Record<string, string>;
  category: string;
  free: boolean;
  python?: boolean;
  bridge?: boolean;
  autoApprove?: string[];
}

export async function removeCommand(mcpId: string) {
  try {
    await runRemove(mcpId);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.error(message);
    if (isVerbose() && err instanceof Error && err.stack) {
      console.error(err.stack);
    }
    process.exit(1);
  }
}

async function runRemove(mcpId: string) {
  const config = await loadConfig();
  if (!config) {
    log.error('No existing configuration found. Run `f2g-telco init` first.');
    process.exit(1);
  }

  const registry = await fs.readJson(path.join(registryDir, 'mcps.json'));
  const mcp: McpEntry | undefined = registry.mcps.find((m: McpEntry) => m.id === mcpId);

  if (!mcp) {
    log.error(`MCP "${mcpId}" not found in registry`);
    process.exit(1);
  }

  if (!config.installedMcps.includes(mcpId)) {
    log.warn(`${mcp.name} is not installed`);
    return;
  }

  const home = os.homedir();
  const userPrefix = path.join(home, '.local');

  // Uninstall the MCP (best effort)
  try {
    if (mcp.python) {
      execSync(`pip3 uninstall -y ${mcp.install.replace('pip install ', '')}`, { stdio: 'pipe', timeout: 120_000 });
    } else {
      const packageName = mcp.install.replace('npm install -g ', '');
      execSync(`npm uninstall --prefix "${userPrefix}" ${packageName}`, { stdio: 'pipe', timeout: 120_000 });
    }
    log.success(`${mcp.name} uninstalled`);
  } catch {
    log.warn('Uninstall failed or not installed globally — continuing to remove from config');
  }

  const paths = getToolPaths(config.tool);

  if (config.tool === 'crush') {
    await removeFromCrushConfig(mcp, paths.mcpConfig);
  } else if (config.tool === 'kiro') {
    await removeFromKiroConfig(mcp, paths.mcpConfig);
  }

  config.installedMcps = config.installedMcps.filter(id => id !== mcpId);
  await saveConfig(config);

  await updateInventory(config.paths.inventory, config.installedMcps, registry.mcps, config.tool);

  log.success(`${mcp.name} removed successfully!`);
  log.dim(`  Restart your ${config.tool} session to reload MCPs.`);
}

async function removeFromCrushConfig(
  mcp: McpEntry,
  configPath: string,
): Promise<void> {
  if (!(await fs.pathExists(configPath))) {
    log.warn(`Crush config not found at ${configPath}`);
    return;
  }

  const config = await fs.readJson(configPath);
  const mcpConfig = (config.mcp as Record<string, unknown>) || {};
  delete mcpConfig[mcp.id];
  config.mcp = mcpConfig;

  const permissions = (config.permissions as { allowed_tools?: string[] }) || { allowed_tools: [] };
  let allowedTools = permissions.allowed_tools || [];

  if (mcp.autoApprove && mcp.autoApprove.length > 0) {
    const removeSet = new Set(mcp.autoApprove.map(tool => `mcp_${mcp.id}_${tool}`));
    allowedTools = allowedTools.filter(tool => !removeSet.has(tool));
  }

  config.permissions = { allowed_tools: allowedTools };

  await fs.writeJson(configPath, config, { spaces: 2 });
  log.success(`Updated ${configPath}`);
}

async function removeFromKiroConfig(
  mcp: McpEntry,
  configPath: string,
): Promise<void> {
  if (!(await fs.pathExists(configPath))) {
    log.warn(`Kiro config not found at ${configPath}`);
    return;
  }

  const config = await fs.readJson(configPath);
  const mcpServers = (config.mcpServers as Record<string, unknown>) || {};
  delete mcpServers[mcp.id];
  config.mcpServers = mcpServers;

  await fs.writeJson(configPath, config, { spaces: 2 });
  log.success(`Updated ${configPath}`);
}

async function updateInventory(
  inventoryPath: string,
  installedIds: string[],
  allMcps: McpEntry[],
  tool: string,
): Promise<void> {
  const rows = allMcps
    .filter(m => installedIds.includes(m.id))
    .map(m => `| ${m.name} | ${m.description} |`)
    .join('\n');

  await fs.writeFile(inventoryPath, `# AI Environment Inventory
> Generated by F2G-Telco v0.1.0. Agents: read this to know what's available.

## MCP Servers (active)
| Server | Purpose |
|--------|---------|
${rows}

## Skills Discovery
Skills are in the tool's skills directory. Each has a SKILL.md with a \`description\` field.
Match task to skill by reading descriptions. Do NOT preload all skills.

## Key Rules
- **gitnexus**: Run \`npx gitnexus analyze\` in a repo before querying
- **context7**: Use for up-to-date library documentation
- **sequential-thinking**: Use for complex multi-step reasoning
- **mem0**: Check for prior context before starting work
- **contextgraph**: Use for structured recall with entity relationships

---
*Tool: ${tool} | Generated: ${new Date().toISOString().split('T')[0]} | F2G-Telco v0.1.0*
`);
  log.success('Updated INVENTORY.md');
}
